[miner]
# Default placement path, can be empty to rely on auto-detection in miners/lolminer/lolMiner.exe
exe = ""
# ETC mining with lolMiner
args = [
  "--algo", "ETCHASH",
  "--pool", "etc.2miners.com:1010",
  "--user", "0x8b55C6A92eD1ac90eF8CAf3dc188255E13B42B88.worker"
]

[server]
host = "127.0.0.1"
port = 8000

[install]
github_repo = "Lolliedieb/lolMiner-releases"
install_dir = "miners/lolminer"
checksums_file = "installers/checksums.toml"
